export interface IPost{
    id?:string,
    type:string,
    name:string,
    description:string,
    img: string,
    img2?: string,
    contact1: string,
    contact2?: string,
    user_id: string,
    latitude?: number,
    longitude?: number,
    gender: string,
    status: string,
    age_id:string,
    disaperAt?: Date|string,
    foundAt?: Date|string,
    localFound?: string,
    localDisaper?:string,
    city_id: string, 
    createdAt?: Date|string,
}